### PR TITLE
Fix audio

### PR DESCRIPTION
**Pull request by captbaritone**
Fixes https://github.com/captbaritone/webamp/issues/993

### CODE REVIEW

**Comment by captbaritone** [comment]
Looks like something a little funky happened here. I only intended to include the one commit here: https://github.com/aawajjoshi/adios/pull/1/commits/166f48e24c11a8b4ad1c904ea0060471b1d442b1

**Comment by captbaritone** [comment]
Maybe you force pushed between the time that I forked and when I opened this PR?

**Comment by aawajjoshi** [comment]
I did. Passing the url as a string resolved the issue. Thank you so much for taking the time to look at it. II'll make sure to not pass it as an object or directly using `url: '../assets/name-of-track.mp3'` in the future. Thanks for making such an awesome library :)

**Comment by captbaritone** [comment]
I’m glad it was an easy fix!

**Pull request merged**
